TRANSLATION.md
As mentioned on #2, I've added a TRANSLATION.md file to host a quickstart guide for new/returning translators, reference links, as well as a translated version of the Universal Style Guide.
=> added TRANSLATION.md

content/docs/thinking-in-react.md
This is the translated version of *Thinking in React*. I took some of the translations already available on the [Crowdin](https://crowdin.com/project/react), with some changes to follow the style guide. I'm going to add some personal notes for the reviewers to look at.
=>  Translate "Thinking in React"

content/docs/cdn-links.md
=> CDN Links translation

content/docs/introducing-jsx.md, content/home/examples/a-simple-component.md
=> docs: change sintaks to sintaksis

content/tutorial/tutorial.md
Hello guys! Finally manage to translate the tutorial page. 
Kindly please review. Thank you
PS: I am not translating React terms like _props_ and _state_ and class names.
=> Translate Tutorial Page

content/docs/reference-react.md
I have done translating this section, please kindly check the content
=> translate React API Reference

content/docs/faq-styling.md
=> translating styling

content/docs/hooks-overview.md
Restoring progress from #34, this PR translates the "Hooks at a Glance" page.
=> Translate Hooks at a Glance

content/warnings/special-props.md
Dear Maintainers, i propose PR in Special Props. Please review this work and give me feedback. Thank you for giving me chance to join this project.
=> Translate Warnings/special-props

content/warnings/invalid-aria-prop.md
=> Translate Warnings/invalid-aria-prop

content/docs/how-to-contribute.md
Translated [How to Contribute](https://reactjs.org/docs/how-to-contribute.html) page.
Please kindly review my work.
Thanks!
=> Translate How to Contribute

content/docs/codebase-overview.md
Translated [Codebase Overview](https://reactjs.org/docs/codebase-overview.html) page.
Please kindly review my work.
Thanks!
=> Translate Codebase Overview

content/docs/integrating-with-other-libraries.md
Please to review my work and thank you for giving me chance to contribute, here's translation for [Integrating with other libraries](https://reactjs.org/docs/integrating-with-other-libraries.html) pages to Indonesia language.
=> Translate Integrating with Other Libraries

content/docs/context.md, examples/context/motivation-problem.js, examples/context/motivation-solution.js, examples/context/multiple-contexts.js, examples/context/theme-detailed-app.js, examples/context/theme-detailed-theme-context.js, examples/context/updating-nested-context-app.js, examples/context/updating-nested-context-context.js, examples/context/updating-nested-context-theme-toggler-button.js
Hi @resir014 and teams. I have done, please review it. Thanks
=> Translate Context

content/docs/testing.md
Hello guys, Please review and give me some feedback for this translation.
=> Translate Testing Overview

gatsby-config.js, src/components/CodeEditor/CodeEditor.js, src/pages/index.js
Translating all the content and UI elements that appear on the index
page.* Also added some missing translations in the Live JSX editor.
(*minus header)
=> Translate Index Page

content/tutorial/nav.yml
This is the translation for tutorial/nav.yml
=> Translate tutorial nav.yml

src/components/MarkdownPage/MarkdownPage.js
So I don't have to URL-edit in browser
=> Point to the correct repo, and use simply 'Edit'

content/docs/how-to-contribute.md
Fixes in how-to-contribute, the one I said in #152
=> how-to-contribute fixes

content/docs/reference-react-component.md
=> Translate React.Component

content/docs/getting-started.md, content/docs/handling-events.md, content/docs/hooks-reference.md, content/docs/rendering-elements.md
=> Delete unresolve conflict paragraphs

content/docs/faq-state.md
Translated FAQ Component State page.
Please kindly review my PR.
Thanks!
=> Translate FAQ Component State

content/docs/thinking-in-react.md
when i read the documentation, i found a typo that confused me.
=> Fix a typo word 'inStockOnlt'

content/docs/concurrent-mode-adoption.md
This is my first translation, any advice and suggestions are greatly appreciated! 🍻   
If I do some mistake, please let me know! Thank you very much 👍
=> Translate Adopting Concurrent Mode

src/content/learn/installation.md
Hi, this is a PR for #330 
for the Installation page under the Installation chapter
=> New Indonesia translation: Installation page

src/content/learn/your-first-component.md
Hi, this is a Pull Request for #330
Translation for Describing The UI -> Your First Component.
=> New Indonesian Translation: Your First Component

src/content/learn/react-developer-tools.md
Hi, this PR is for #330 
Translation for `React Developer Tools` page under installation section.
=> New Indonesian Translation: React Developer Tools

src/content/reference/react/useContext.md
Closes #463 
Translation for useContext docs reference by #330
=> translation for useContext

src/content/reference/react/memo.md
Translation for page https://id.react.dev/reference/react/memo
Isssues: https://github.com/reactjs/id.react.dev/issues/418
Related with :
- https://github.com/reactjs/id.react.dev/issues/330
Closes #418
=> docs: translations for APIs memo

src/content/reference/react/forwardRef.md
Translation for forwardRef reference
Closes #470
=> docs: translation for forwardRef

.github/workflows/analyze.yml, .github/workflows/analyze_comment.yml, src/components/Layout/HomeContent.js, src/content/community/conferences.md, src/content/reference/react-dom/createPortal.md, src/content/reference/react/Component.md, src/content/reference/react/Fragment.md, src/content/reference/react/useMemo.md
Reverts reactjs/id.react.dev#490
=> Revert "Sync with react.dev @ 8ed23b1a"

.github/workflows/analyze.yml, .github/workflows/analyze_comment.yml, src/components/Layout/HomeContent.js, src/content/community/conferences.md, src/content/reference/react-dom/createPortal.md, src/content/reference/react/Component.md, src/content/reference/react/Fragment.md, src/content/reference/react/useMemo.md
Turns out the regular merge commit for syncing #490 works fine (unlike what I initially thought) so we reverted said revert.
Reverts reactjs/id.react.dev#491
=> Revert previous accidental revert

src/content/reference/react/useLayoutEffect.md
Translating `useLayoutEffect` to Indonesian 
Status: Ready for proofreading
Closes https://github.com/reactjs/id.react.dev/issues/405
=> docs: translations for `useLayoutEffect` hook

src/content/learn/updating-objects-in-state.md
=> docs: initial indonesia translation for page Updating Objects in State

src/content/learn/rendering-lists.md
Closes #466
This PR is issued for the translation of `Rendering Lists` page into Indonesian.
=> docs: translate Rendering Lists page

src/content/reference/react/useTransition.md
Apologies for any mistranslation or misspelling terms. It's my first time doing Open Source project so any critiques and suggestions are very welcome!
Page: https://id.react.dev/reference/react/useTransition
Closes #411
=> Translation for `Hooks` : `useTransition`

src/content/learn/describing-the-ui.md, src/content/learn/importing-and-exporting-components.md, src/content/learn/tutorial-tic-tac-toe.md, src/content/reference/react/createContext.md, src/content/reference/react/memo.md, src/content/reference/react/useContext.md, src/content/reference/react/useLayoutEffect.md, src/content/reference/react/useTransition.md
Based on our discussion about "merender" and "me-render"
=> docs: changes merender to me-*render*

src/content/learn/thinking-in-react.md
Translated the "Thinking in React" page to Indonesian.
Closes #374.
=> docs: translate Thinking in React

src/content/learn/passing-props-to-a-component.md, src/content/learn/react-developer-tools.md
Closes #428 
Translation of [Passing Props to a Component](https://id.react.dev/learn/passing-props-to-a-component)
Reference: #330
=> docs: translation of `Passing Props to a Component`

TRANSLATION.md
Context: https://github.com/reactjs/id.react.dev/issues/427#issuecomment-1529905299
=> docs(translation): emphasize assignment mechanism and PR prioritization

src/content/learn/referencing-values-with-refs.md
Closes https://github.com/reactjs/id.react.dev/issues/387
=> docs: translate Referencing Values with Refs page

src/content/learn/updating-arrays-in-state.md
Indonesian translation for Updating Arrays in State page
Closes #451
=> docs: translation for Updating Arrays in State page

src/content/reference/react-dom/createPortal.md
Closes https://github.com/reactjs/id.react.dev/issues/436
=> docs: translation for reference/react-dom/createPortal (#436)

src/content/learn/reusing-logic-with-custom-hooks.md
Translation to Bahasa for Reusing Logic with Custom Hooks.
Issue: #330
Closes #394
=> docs: translation for reusing logic with custom hooks

src/content/reference/react/PureComponent.md
Closes #553 
Translate the PureComponent page.
Page URL: https://id.react.dev/reference/react/PureComponent
=> docs: translate PureComponent page

src/content/learn/add-react-to-an-existing-project.md
=> Translate Add React To an Existing Project to Bahasa

src/content/reference/react/createElement.md
Closes #549 
Translate the Reference > Legacy APIs > createElement page.
Page URL: https://id.react.dev/reference/react/createElement
=> docs: translate Legacy APIs > `createElement`

src/content/reference/react-dom/components/input.md
Closes #423
Translation to Bahasa for Input in React Dom.
Reference: #330
=> docs: translation for input in react dom

src/content/reference/react-dom/flushSync.md
Closes #438
Translate the `flushSync` page.
Page URL: https://id.react.dev/reference/react-dom/flushSync
=> docs: translate `react-dom` -> `flushSync`

src/components/Layout/TopNav/TopNav.tsx
Closes #584
Translate the top nav component.
Page URL: N/A
=> docs: translate top nav

src/content/learn/preserving-and-resetting-state.md
Closes #382 
Translate the **Preserving and Resetting State** page.
Page URL: https://id.react.dev/learn/preserving-and-resetting-state
=> docs: translate Preserving and Resetting State

src/components/Layout/Feedback.tsx
Closes #590
Translate the feedback box layout component.
Page URL: N/A
=> docs: translate feedback button component

src/components/Layout/Footer.tsx
Closes #591
Translate the Footer component.
Page URL: N/A
=> docs: translate footer component

src/content/learn/responding-to-events.md, src/sidebarLearn.json
Closes #445 
Translate the Responding to Events page.
Page URL: https://id.react.dev/learn/responding-to-events
=> docs: translate responding to events page

src/components/SocialBanner.tsx
Closes #604
Translate the Social Banner component.
Page URL: N/A
=> docs: translate social banner component

src/content/reference/react/Children.md
Fixes #546 and closes #573.
This PR adds translation to "Children" page, continuing @ilham89 effort.
Translate the Suspense page.
Page URL:
- 🌍: https://react.dev/reference/react/Children
- 🇮🇩: https://id.react.dev/reference/react/Children
=> docs: translate Children

src/content/learn/reacting-to-input-with-state.md
Fixes #379 and closes #532.
Translate the Reacting to Input with State page, continuing @JfrAziz's effort on translating the page.
Page URL:
- 🌍: https://react.dev/learn/reacting-to-input-with-state
- 🇮🇩: https://id.react.dev/learn/reacting-to-input-with-state
=> docs: translate Reacting to Input with State

src/content/reference/rules/rules-of-hooks.md
Closes #654
Translate the Rules of Hooks page.
Page URL: https://id.react.dev/reference/rules/rules-of-hooks
=> docs: translate Rules of Hooks

src/content/learn/typescript.md
Closes #658
Translate the Using TypeScript page.
Page URL: https://id.react.dev/learn/typescript
=> docs: translate Using TypeScript

src/content/reference/react-dom/preconnect.md
Closes  #691 
Translate the  page.
Page URL: https://id.react.dev/reference/react-dom/preconnect
=> docs: translate for `preconnect` page (#691)

src/content/learn/react-compiler.md, src/sidebarLearn.json
Closes [#703](https://github.com/reactjs/id.react.dev/issues/703)
Translate the React Compiler page.
Page URL: https://id.react.dev/learn/react-compiler
=> docs: translate page React Compiler

src/content/reference/react-dom/prefetchDNS.md, src/content/reference/react/act.md
Closes #675 
Translate the **Act** page.
Page URL: https://id.react.dev/reference/react/act
=> docs: translate 'act'
