reactjs/id.react.dev

README.md
The instruction in https://github.com/reactjs/id.reactjs.org#push-it section still refers to the original English repo. I changed it to current repo's (Indonesian) link.
=> Updated reactjs.org repo link to Indonesian one

content/docs/composition-vs-inheritance.md
Translated Composition vs Inheritance page
=> Translate Composition vs Inheritance

content/docs/typechecking-with-proptypes.md
Not sure about certain words.... Anyway....
=> Translate typechecking-with-proptypes

content/docs/lifting-state-up.md
=> docs:Basic - Lifting State Up

content/warnings/dont-call-proptypes.md
=> warnings(dont-call-proptypes): translate dont call proptypes

content/warnings/unknown-prop.md
Dear maintainers, please review the changes I've proposed in the PR and give me feedback. Thank you.
=> Translate Warnings/unknown-prop

content/warnings/invalid-hook-call-warning.md
Dear Maintainers, i propose PR in Translating  Invalid hook call warning. Please review this work and give me feedback.
=> Translate Warnings/invalid-hook-call-warning

content/warnings/refs-must-have-owner.md
=> Translate Warnings/refs-must-have-owner

content/docs/fragments.md
=> Translate Fragments

content/docs/faq-internals.md
Originally this part was claimed by @mekhanix, but since there was no update from the original claimer, I decided to help out. **Please forgive my rudeness**. And please review my translation.
=> Translate Virtual DOM and Internals

content/warnings/legacy-factories.md
Dear Maintainer, Please give me some feedback for this translation.
=> Translate Warnings/legacy-factories

src/components/CodeEditor/CodeEditor.js, src/components/CodeExample/CodeExample.js, src/components/ErrorDecoder/ErrorDecoder.js, src/components/LayoutFooter/Footer.js, src/components/LayoutHeader/DocSearch.js, src/components/MarkdownPage/MarkdownPage.js
Hi everyone, here is my first PR for this project in `components` part. Thank you.
cc: @resir014
=> Translate components

content/docs/reconciliation.md
Hi guys, I was completely translating Reconciliation page. Please review this and give me a feedback. :smile:
=> Translate Reconciliation

content/docs/portals.md, content/docs/react-without-es6.md, content/docs/react-without-jsx.md, content/docs/reference-test-renderer.md, content/docs/refs-and-the-dom.md, content/docs/static-type-checking.md, content/docs/uncontrolled-components.md
**NOTE: Do not squash merge this PR.**
This PR merges in all the old inactive PRs and applies all the suggested changes from said PRs where possible.
Lists of all the PRs that are being merged in:
**@lunmay**
- #47 
- #48 
- #49 
- #50 
- #51 
**@rianonehub**
- #21 
**@brilyandk**
- #55
=> Merge + apply review fixes to all inactive docs contributions

content/docs/react-without-jsx.md
=> React Without JSX

content/docs/react-without-es6.md
=> Translated React Without ES6

content/docs/static-type-checking.md
=> Translated Static Type Checking

content/docs/refs-and-the-dom.md
=> Translated Refs and The DOM

content/docs/portals.md
=> Translated Portals

content/docs/faq-structure.md
Please kindly review my work, thanks.
=> Translate File Structure

content/docs/error-boundaries.md
=> Translate Error Boundaries

content/docs/higher-order-components.md
Dear maintainers,
Please review this translation. I have several concerns about some term which i am confused to translate. They are: 
- Subscribe
- data source
- Wrapped component
- inheritance
- container
- Children
Please help me solve that @resir014 @regalius
=> Translate higher order components

content/docs/concurrent-mode-intro.md
Translated **Introducing Concurrent Mode** page.
Please kindly review my work.
Thanks!
=> Translate Introducing Concurrent Mode

content/docs/optimizing-performance.md
Hi,
recently, I read the documentation and I've found this typo word. The word "khisis" should be "khusus" right?
=> Fix word typo "khisis" in optimizing performance content

content/docs/testing-environments.md
Hi, please review this translation
testing-environment,
Thank You 👍🏼
=> feat: translate - testing-environments ID

content/docs/render-props.md
I've posted in the glossary discussion section for some terms I am not sure about, I haven't got any comments yet so I think I'll just create this PR first anyway.. hope it suffices!
=> Translate Render Props

content/docs/nav.yml
=> Translate docs/nav.yml

content/docs/concurrent-mode-reference.md
Happy to welcome any feedback!
Cheers
=> concurrent mode reference translation

content/docs/forwarding-refs.md, examples/forwarding-refs/customized-display-name.js, examples/forwarding-refs/fancy-button-ref.js, examples/forwarding-refs/fancy-button-simple-ref.js, examples/forwarding-refs/fancy-button.js, examples/forwarding-refs/log-props-after.js
Translating **Forwarding Refs** page, as listed at #1 .
Continue translating from [darmawanalbert's](https://github.com/reactjs/id.reactjs.org/pull/197) pull request
=> Translate Forwarding Refs

src/content/learn/tutorial-tic-tac-toe.md
Started work on translating the Tic-Tac-Toe tutorial to Indonesian.
=> New Indonesian translation: Tutorial: Tic-Tac-Toe

src/content/reference/react/createContext.md
Translation for `createContext` https://github.com/reactjs/id.react.dev/issues/330
=> translation for createContext

src/content/learn/start-a-new-react-project.md
Closes #376 
Hi @resir014 @r17x sorry this is the PR revision of #344.
For the [Start a New React Project page](https://react.dev/learn/start-a-new-react-project) under the Installation chapter.
Also, the suggestions from @r17x have been done
=> New Indonesian Translation: Start a New React Project

src/content/learn/your-first-component.md
- Based on the [original documentation](https://react.dev/learn/your-first-component), it using "JavaScript" spelling instead of "Javascript".
- Does "JavaScript" word need to using *italic* style? I remove it because I think it was unnecessary.
=> docs: use consistent capitalisation of "JavaScript"

src/content/reference/react-dom/components/index.md
Translation for `react-dom: Components` overview page. Referenced by [#330 ](https://github.com/reactjs/id.react.dev/issues/330#issuecomment-1525164524)
Closes #421
=> docs: translation for `react-dom: Components` Overview Page

src/content/reference/react/useRef.md
Translation for API Reference / Hooks / useRef, referenced by #330
Closes #408
=> docs: translation for useRef

src/content/learn/keeping-components-pure.md
This PR is created to translate `Keeping Components Pure` page to Indonesian.
Related to #330 
Closes #435
=> docs: translate Keeping Components Pure page

src/content/learn/tutorial-tic-tac-toe.md, src/content/reference/react/apis.md, src/content/reference/react/memo.md, src/content/reference/react/useContext.md, src/content/reference/react/useLayoutEffect.md
Related with #503 
| from | to |
| - | - |
| dirender | di-*render* |
=> docs: changes dirender to di-*render*

src/content/learn/render-and-commit.md
Hello, this PR docs reference by #330, translation for `render and commit` section under `Adding Interactivity`. 
Closes #447 
Thank you.
=> docs: add translation for render-and-commit

src/content/reference/react-dom/index.md
Closes #434
Hello there, this is my pull request for translating the file located at `src/content/reference/react-dom/index.md`.
=> New Indonesian translation: react-dom: APIs

src/content/reference/react/startTransition.md
Menambahkan terjemahan Bahasa Indonesia untuk `startTransition`.
Resolves #420.
=> Translation of `startTransition`

src/content/reference/react-dom/server/index.md
Translation for react-dom/server: Server APIs (en -> id)
Closes https://github.com/reactjs/id.react.dev/issues/456
=> docs: translations react-dom/server: Server APIs

src/content/reference/react-dom/server/renderToStaticNodeStream.md
Closes https://github.com/reactjs/id.react.dev/issues/461
translation to Bahasa for renderToStaticNodeStream.
Reference: https://github.com/reactjs/id.react.dev/issues/330
=> docs: translating renderToStaticNodeStream

src/content/learn/adding-interactivity.md
Added translations for `Adding Interactivity: Overview` page.
Closes #452
=> docs: Adding Interactivity Overview translations

TRANSLATION.md
Closes 
Hallo, maaf untuk kontribusi yang sangat kecil.
Disini saya hanya menambahkan `src/content` mungkin untuk pemula seperti saya akan kebingungan mencari dimana leta lokasi `content` secara default.
=> docs(translation): use correct path for `content` folder

src/content/reference/react/useCallback.md
translations for page: https://react.dev/reference/react/useCallback
Closes #398
=> docs translations: useCallback

src/content/learn/writing-markup-with-jsx.md
Translate `writing-markup-with-jsx.md`
Related page: https://react.dev/learn/writing-markup-with-jsx
Closes #419
=> Translate Writing Markup with JSX

src/content/learn/scaling-up-with-reducer-and-context.md
Closes #385 
translation for scaling up with reducer and context docs reference by #330
=> translation for scaling up with reducer and context

src/content/reference/react-dom/server/renderToStaticMarkup.md, src/content/reference/react/startTransition.md
Menambahkan terjemahan Bahasa Indonesia untuk `renderToStaticMarkup`.
Resolves #460.
=> Translation of `renderToStaticMarkup`

src/content/reference/react/useDebugValue.md
Closes #399 
- update: translate `hooks:useDebugValue` page
=> update: translate `useDebugValue`

src/content/reference/react-dom/components/progress.md
Hi, this is a Pull Request for https://github.com/reactjs/id.react.dev/issues/330
Translation for page https://react.dev/reference/react-dom/components/progress
Closes #426
=> docs: translations for components progress

src/content/learn/conditional-rendering.md
Closes #431
Translate the **Conditional Rendering** page.
Page URL: https://id.react.dev/learn/conditional-rendering
=> docs: translate Conditional Rendering

src/content/reference/react/lazy.md
Translation for page https://id.react.dev/reference/react/lazy
Closes #471
=> docs: translate API Reference > APIs > `lazy`

src/content/reference/react/forwardRef.md
Closes #470
Adjust translations of the`forwardRef` API page. (adjustments based on feedbacks in #518, #337, and https://github.com/reactjs/id.react.dev/wiki/Glosarium)
Page URL: https://id.react.dev/reference/react/forwardRef
=> docs(translation): adjust `forwardRef` docs translation

src/content/reference/react-dom/server/renderToNodeStream.md
=> docs: translate the `renderToNodeStream` section

src/content/reference/react-dom/components/select.md
Closes #427 
Translate the `select`  page.
Page URL: https://id.react.dev/reference/react-dom/components/select
=> docs: translation for react-dom components `<select>`

src/content/learn/manipulating-the-dom-with-refs.md
Closes #388 
This PR is aimed at resolving the task of translating the "Manipulating the DOM with Refs" page.
=> Translate Manipulating the DOM with Refs page

TRANSLATION.md
This PR changes the references to the style guide, so only the Indonesian version is used. The English version is deprecated and will soon be deleted.
New link for Indonesian style guide is at: https://github.com/reactjs/id.react.dev/wiki/Panduan-Penulisan-Umum
=> docs: change the link to style guide

src/content/learn/index.md
Closes #372
Fix the typo on the **Quick Start** page.
Page URL: https://id.react.dev/learn
=> Fix typo on Quick Start

src/content/learn/index.md
Closes #559
Translate the Quick Start page.
Page URL: https://id.react.dev/learn
=> docs: fix links not working on the Quick Start page

src/content/reference/react/legacy.md
Closes #545
Translate the Legacy React APIs page.
Page URL:  https://id.react.dev/reference/react/legacy
=> docs: translate Legacy React APIs

src/content/reference/react-dom/components/textarea.md
Closes #433
Translate the textarea section into Bahasa
Reference page: https://id.react.dev/reference/react-dom/components/textarea
=> docs: translate `<textarea>` reference

src/content/reference/react-dom/server/renderToString.md
=> docs: translate `renderToString` section

src/content/reference/react/createRef.md
Closes #551 
Translate the `createRef` page.
Page URL: https://id.react.dev/reference/react/createRef
=> docs: translate `react-dom` -> `createRef`

src/content/reference/react/StrictMode.md
Closes #415
Translate the StrictMode page.
Page URL: https://id.react.dev/reference/react/StrictMode
=> docs: translate API Reference -> `react` -> `<StrictMode>`

src/sidebarHome.json, src/sidebarLearn.json, src/sidebarReference.json
Closes https://github.com/reactjs/id.react.dev/issues/583
Translate the `src/sidebar*.json`
=> docs: translate documentation sidebar at `src/sidebar*.json`

src/content/reference/react-dom/findDOMNode.md
Fixes #439 and closes #510
This PR adds translation to `findDOMNode` page, continuing @afrianjunior's effort.
Translate the `findDOMNode` page.
Page URL:
- 🌍: https://react.dev/reference/react-dom/findDOMNode
- 🇮🇩: https://id.react.dev/reference/react-dom/findDOMNode
=> docs: translate API Reference -> Legacy -> `findDOMNode`

src/content/reference/react-dom/unmountComponentAtNode.md
Fixes #443 and closes #512.
This PR adds translation to `unmountComponentAtNode` page, continuing @afrianjunior's effort.
Translate the `unmountComponentAtNode` page.
Page URL:
- 🌍: https://react.dev/reference/react-dom/unmountComponentAtNode
- 🇮🇩: https://id.react.dev/reference/react-dom/unmountComponentAtNode
=> docs: translate `unmountComponentAtNode`

src/components/Layout/Footer.tsx, src/content/learn/escape-hatches.md, src/sidebarHome.json, src/sidebarLearn.json
Closes https://github.com/reactjs/id.react.dev/issues/386
Translate the escape hatches page.
Page URL: https://react.dev/learn/escape-hatches
=> docs: translate introduction of escape hatches

src/content/reference/react/index.md
Closes #650 
Translate the "React Reference Overview" page.
Page URL: https://id.react.dev/reference/react
=> docs: translation react reference overview #650

src/content/reference/rules/index.md
Closes #651
Translate the Rules of React page.
Page URL: [id.react.dev/reference/rules](https://id.react.dev/reference/rules)
=> docs: translate 'Rules of React'

.vscode/settings.json, src/content/reference/react/cache.md
Closes #676 
Translate the reference/react/cache
Page URL: https://id.react.dev/reference/react/cache
=> docs: translate `cache`

src/content/reference/react-dom/components/title.md
Closes  #690  
Translate the `<title>` page.
Page URL: https://id.react.dev/reference/react-dom/components/title
=> docs: `title` component translation

src/content/reference/react-dom/hooks/index.md
Closes #678 
Translate the Built-in React DOM Hooks page.
Page URL: https://id.react.dev/reference/react-dom/hooks
=> docs: translate built-in react-dom hooks

src/content/reference/react-dom/prefetchDNS.md
Closes #692
Translate the `prefetchDNS` page.
Page URL: https://id.react.dev/reference/react-dom/prefetchDNS
=> docs: translate page `prefetchDNS`

src/content/reference/react-dom/preload.md
Closes #695 
Translate the  page.
Page URL:
=> docs: translate `preload` page

src/content/reference/react-dom/hooks/useFormStatus.md
Closes #679 
Translate the useFormStatus page.
Page URL: https://id.react.dev/reference/react-dom/hooks/useFormStatus
=> docs: `useFormStatus` hook translation

src/content/reference/rsc/directives.md
Closes #699  
Translate the Directives page.
Page URL: https://id.react.dev/reference/rsc/directives
=> docs: translate directives page

src/content/reference/react/useActionState.md
Closes https://github.com/reactjs/id.react.dev/issues/682
Translate the /reference/react/useActionState page.
Page URL: https://id.react.dev/reference/react/useActionState
=> docs: translate `useActionState`

src/content/reference/react/useOptimistic.md
Closes #683 
Translate the useOptimistic reference page.
Page URL: https://id.react.dev/reference/react/useOptimistic
=> docs: translate `useOptimistic`

src/content/reference/rsc/use-client.md, src/content/reference/rsc/use-server.md
Closes #700
Translate the `'use client'` page.
Page URL: https://id.react.dev/reference/rsc/use-client
=> docs: translate `'use client'`
